### ISSUE TITLE
implement restart

### ISSUE THREAD

**Issue by lipanski** [immortal/immortal#19]
I'm missing a restart command that would restart my process without having to run two commands (halt and up). I mainly require this for reloading application-specific configuration files.

I guess a restart command would basically mean calling `immortalctl halt xxx` and then start the process again. it would probably only work when using `immortaldir`.

would be nice to expose the sequence of commands for restart as part of the configuration (pretty much like Monit does it?!), in case sending the `TERM` signal is not my way of restarting a process.

wdyt? :pineapple:

**Comment by nbari** [comment]
Currently If using `immortaldir` by just changing the contents of the config file `run.yml` it will automatically restart the process, so basically is already doing a  stop/start sequence,  by sending a TERM signal and exiting the supervisor and later just start all over again.

In some cases, you may want to prevent the process to start so if you remove read rights,  `chmod 000 foo.yml` the process won't start again, because `immortaldir` can't access the file,  but after you just set the perms back to `chmod 644 foo.yml`  the process automatically will start again.

you can also touch the directory and that will force a start in all the files within the directory:

    touch /usr/local/etc/immortaldir

In any case, I will try to see how to make this more user-friendly.

About exposing a sequence of commands for restart, if you need something custom or if monit is already doing that for you, maybe could be easier to continue using it, mainly because it works out of the box with `immortal` without need to create a custom `reset` option, indeed you could just basically focus only on how to stop your process and `immortal` automatically once detects your process is down it will bring it up.

**Comment by nbari** [comment]
Hi @lipanski please give a try to the latest version [0.14.0](https://github.com/immortal/immortal/releases/tag/0.14.0) 

To do a "restart" you will just need to `immortalctl halt xxx` and if using `immortaldir`, it will automatically reload the service after 1 second.

What is new in this version is that `immortaldir` watch now for changes in `IMMORTAL_SDIR` so that there is a certain guarantee that the defined services are always up and running.

Hope this helps and thanks for testing.
