### ISSUE TITLE
Have a lot of Defunct process when running immortal in a docker container

### ISSUE THREAD

**Issue by geraldatphotobucket** [immortal/immortal#45]
I had some missing libraries in my container so my process kept dying, but this seemed to create a lot of defunct process when I log into the container.

I run my command as 
immortal -l /dev/null /usr/bin/python3 <my python script>

in the container immortal has pid 1.   Is there something I need to do to avoid these defunct entries in the container (and presumably host) pid table?

**Comment by nbari** [comment]
hi @geraldatphotobucket check this https://github.com/immortal/immortal/issues/23 probably could give you some ideas if want to use `immortal` within docker also (https://github.com/nbari/docker/tree/master/immortal)

From your command probably you may want to run a script, not the `python3` binary since that will just create a loop trying to run  every time `python3` if exists, probably someting like this:

    immortal /path/to/your/script.py
